apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: test
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sh
      - -c
      - |
        #!/bin/bash
        while true
        do
          echo "hello world"
          sleep 5
        done